{
  "ae29332c9ebe9b791fd2a56ddfe90d31" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 0,
      "unknown" : 0,
      "total" : 1
    },
    "items" : [ {
      "uid" : "4b1022755f864b3a",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbb2a859220>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1714648982153,
        "stop" : 1714648982153,
        "duration" : 0
      }
    } ]
  },
  "6f0cac2001dc3bff365c00709d709434" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 0,
      "unknown" : 0,
      "total" : 1
    },
    "items" : [ {
      "uid" : "29bd0735799f5d13",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbb2b0e6ab0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1714648981898,
        "stop" : 1714648981898,
        "duration" : 0
      }
    } ]
  },
  "f736e4da79104d16b512e8707930dbca" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 0,
      "unknown" : 0,
      "total" : 1
    },
    "items" : [ {
      "uid" : "2ca0da2bc0c4a836",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbb2a704950>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1714648982040,
        "stop" : 1714648982040,
        "duration" : 0
      }
    } ]
  },
  "98e7380dbfc189a872bc552f301ce74c" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 0,
      "unknown" : 0,
      "total" : 1
    },
    "items" : [ {
      "uid" : "c024349d855fe8ad",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbb2a8e4f80>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1714648982264,
        "stop" : 1714648982264,
        "duration" : 0
      }
    } ]
  }
}